### ISSUE TITLE
Issue with the weeks, 2022

### ISSUE THREAD

**Issue by manalkamal** [Institut-Zdravotnych-Analyz/covid19-data#156]
Dear all, 

Many thanks for continuing providing the data and for all your efforts on this regard. 

Data in this file 'OpenData_Slovakia_Vaccination_AgeGroup_District.csv' for year 2022 are starting by 'week' 54 instead of week 1. Could you kindly confirm if this is correct?

Many thanks.

**Comment by mhudec** [comment]
It seems that the "week" column is basically a number of the week (since the beginning of vaccinations) in which the actual vaccinations happened. And as 2021 turned to 2022, they needed to have also normal (calendar) week... see the picture at [https://imgur.com/YIvhZPA](url), 31st week of 2022 is 83rd week of vaccinations.
